FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .

RUN pip3 install -r requirements.txt

COPY requirements.txt .
COPY pipeline.py .
COPY RAG_embedding.py .
COPY utils/ utils/

CMD ["python", "pipeline.py"]