FROM python:3.13

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY chatbot.py .

EXPOSE 8501

CMD ["streamlit", "run", "chatbot.py", "--server.port", "8501", "--server.headless", "true"]